/**
 * @fileoverview Root Layout Component
 * 
 * Establishes the base HTML structure and typography system for the ALX Polly application.
 * This layout wraps all pages and provides consistent font loading and global styles.
 * 
 * Font Strategy: Uses Geist fonts with CSS variables for consistent typography across
 * the application while maintaining good performance through Next.js font optimization.
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Primary font for body text and UI elements
// CSS variable allows dynamic switching in components if needed
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Monospace font for code blocks, technical content, and data display
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root Layout Component
 * 
 * Provides the foundational HTML structure for all pages in the application.
 * Establishes the typography system through CSS variables and ensures consistent
 * font loading across the entire app.
 * 
 * @param children - All page content and nested layouts
 * @returns The base HTML document structure
 * 
 * @assumptions
 * - All pages require the same base font configuration
 * - Global styles are defined in globals.css
 * - Font variables are used consistently across components
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}

